name: Update Lists
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update:
    name: Update lists
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: "24.x"
      - name: Setup Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Update
        run: |
          node update.js
          git commit -a -m "Update lists"
          git push